# Automatically generated by Pynguin.
import rddsampler_d as module_0

def test_case_0():
    try:
        bool_0 = False
        int_0 = 1282
        r_d_d_sampler_base_0 = module_0.RDDSamplerBase(bool_0, int_0)
    except BaseException:
        pass

def test_case_1():
    try:
        float_0 = None
        bool_0 = False
        r_d_d_sampler_base_0 = module_0.RDDSamplerBase(bool_0)
        int_0 = r_d_d_sampler_base_0.getPoissonSample(float_0)
    except BaseException:
        pass

def test_case_2():
    try:
        bool_0 = True
        r_d_d_sampler_base_0 = module_0.RDDSamplerBase(bool_0)
        float_0 = r_d_d_sampler_base_0.getUniformSample()
    except BaseException:
        pass

def test_case_3():
    try:
        int_0 = 1212
        bool_0 = True
        int_1 = -1003
        float_0 = -430.8
        bool_1 = True
        float_1 = -694.0
        r_d_d_sampler_0 = module_0.RDDSampler(bool_1, float_1)
        assert r_d_d_sampler_0 is not None
        assert module_0.T is not None
        assert module_0.K is not None
        iterator_0 = r_d_d_sampler_0.func(int_1, float_0)
        float_2 = -1355.0
        list_0 = [bool_0, float_2, bool_0]
        bool_2 = True
        float_3 = 82.469
        bool_3 = True
        r_d_d_sampler_1 = module_0.RDDSampler(bool_3, float_3)
        r_d_d_sampler_2 = module_0.RDDSampler(bool_2, float_3)
        iterator_1 = r_d_d_sampler_2.func(int_0, list_0)
        r_d_d_sampler_3 = module_0.RDDSampler(bool_0, float_2, int_0)
        bool_4 = True
        int_2 = 619
        r_d_d_sampler_base_0 = module_0.RDDSamplerBase(bool_4, int_2)
        float_4 = r_d_d_sampler_base_0.getUniformSample()
    except BaseException:
        pass