# Automatically generated by Pynguin.
import geo_utils_d as module_0

def test_case_0():
    try:
        str_0 = ''
        str_1 = None
        str_2 = None
        str_3 = 'CV3M7mLiY '
        int_0 = -296
        spatial_reference_system_cache_0 = module_0.SpatialReferenceSystemCache()
        assert module_0.SpatialReferenceSystemCache.instance is not None
        optional_0 = spatial_reference_system_cache_0.get_srs_by_srid(int_0)
        spatial_reference_system_cache_1 = module_0.SpatialReferenceSystemCache()
        dict_0 = {str_0: str_0, str_1: str_1, str_2: str_1, str_3: str_1}
        geographic_spatial_reference_system_mapper_0 = module_0.GeographicSpatialReferenceSystemMapper(**dict_0)
    except BaseException:
        pass

def test_case_1():
    try:
        int_0 = -709
        list_0 = [int_0]
        str_0 = 'I(+oK\nRM'
        dict_0 = {str_0: int_0}
        cartesian_spatial_reference_system_mapper_0 = module_0.CartesianSpatialReferenceSystemMapper(*list_0, **dict_0)
    except BaseException:
        pass