# Automatically generated by Pynguin.
import geo_utils_d as module_0

def test_case_0():
    str_0 = '$'
    int_0 = 4152
    str_1 = '-88Fw;{{W*'
    bool_0 = True
    spatial_reference_system_information_0 = module_0.SpatialReferenceSystemInformation(int_0, str_1, bool_0)
    assert spatial_reference_system_information_0.srid == 4152
    assert spatial_reference_system_information_0.string_id == '-88Fw;{{W*'
    assert spatial_reference_system_information_0.is_geographic is True
    var_0 = spatial_reference_system_information_0.__hash__()
    spatial_reference_system_cache_0 = module_0.SpatialReferenceSystemCache()
    assert module_0.SpatialReferenceSystemCache.instance is not None
    optional_0 = spatial_reference_system_cache_0.get_srs_by_string_id(str_0)
    int_1 = 454
    optional_1 = spatial_reference_system_cache_0.get_srs_by_srid(int_1)
    int_2 = -316
    geographic_spatial_reference_system_mapper_0 = module_0.GeographicSpatialReferenceSystemMapper()
    str_2 = '<j`NkA{OeD.k+\nE'
    optional_2 = geographic_spatial_reference_system_mapper_0.get_srid(str_2)
    assert spatial_reference_system_cache_0 is not None
    assert optional_0 is None
    assert optional_1 is None
    assert geographic_spatial_reference_system_mapper_0 is not None
    assert optional_2 is None
    assert module_0.annotations.optional == (3, 7, 0, 'beta', 1)
    assert module_0.annotations.mandatory == (3, 11, 0, 'alpha', 0)
    assert module_0.annotations.compiler_flag == 16777216
    spatial_reference_system_cache_1 = module_0.SpatialReferenceSystemCache()
    assert spatial_reference_system_cache_1 is not None
    optional_3 = spatial_reference_system_cache_1.get_srs_by_srid(int_2)
    assert optional_3 is None
    optional_4 = geographic_spatial_reference_system_mapper_0.get_string_id(int_2)
    assert optional_4 is None
    int_3 = -500
    str_3 = ''
    bool_1 = None
    spatial_reference_system_cache_2 = module_0.SpatialReferenceSystemCache()
    assert spatial_reference_system_cache_2 is not None
    optional_5 = spatial_reference_system_cache_2.get_srs_by_srid(int_3)
    assert optional_5 is None
    optional_6 = spatial_reference_system_cache_2.get_srs_by_string_id(str_3)
    assert optional_6 is None
    str_4 = 'p'
    spatial_reference_system_information_1 = module_0.SpatialReferenceSystemInformation(int_3, str_4, bool_1)
    assert spatial_reference_system_information_1.srid == -500
    assert spatial_reference_system_information_1.string_id == 'p'
    assert spatial_reference_system_information_1.is_geographic is None
    var_1 = spatial_reference_system_information_1.__eq__(int_2)
    spatial_reference_system_information_2 = module_0.SpatialReferenceSystemInformation(int_3, str_3, bool_1)
    assert spatial_reference_system_information_2.srid == -500
    assert spatial_reference_system_information_2.string_id == ''
    assert spatial_reference_system_information_2.is_geographic is None