# Automatically generated by Pynguin.
import _inspect_d as module_0
import builtins as module_1

def test_case_0():
    try:
        str_0 = None
        list_0 = [str_0]
        dict_0 = {}
        set_0 = set()
        str_1 = module_0.formatargvalues(list_0, str_0, str_0, dict_0, dict_0, set_0)
    except BaseException:
        pass

def test_case_1():
    try:
        list_0 = []
        str_0 = 'aq+y5*\\'
        dict_0 = {}
        str_1 = module_0.formatargvalues(list_0, str_0, str_0, dict_0, list_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = ']{l)'
        object_0 = module_1.object()
        bool_0 = module_0.isfunction(object_0)
        assert module_0.CO_OPTIMIZED == 1
        assert module_0.CO_NEWLOCALS == 2
        assert module_0.CO_VARARGS == 4
        assert module_0.CO_VARKEYWORDS == 8
        list_0 = [str_0]
        frame_0 = module_1.frame(*list_0)
    except BaseException:
        pass