# Automatically generated by Pynguin.
import exceptions_d as module_0

def test_case_0():
    module_deprecation_warning_0 = module_0.ModuleDeprecationWarning()
    complex_warning_0 = module_0.ComplexWarning()
    int_0 = -3385
    axis_error_0 = module_0.AxisError(int_0)
    assert module_deprecation_warning_0 is not None
    assert complex_warning_0 is not None
    assert axis_error_0 is not None
    str_0 = axis_error_0.__str__()
    assert str_0 == -3385
    str_1 = axis_error_0.__str__()
    assert str_1 == -3385
    int_1 = -2126
    complex_warning_1 = module_0.ComplexWarning()
    assert complex_warning_1 is not None
    int_2 = 522
    axis_error_1 = module_0.AxisError(int_2)
    assert axis_error_1 is not None
    axis_error_2 = module_0.AxisError(int_1, int_1)
    assert axis_error_2 is not None
    str_2 = axis_error_2.__str__()
    assert str_2 == 'axis -2126 is out of bounds for array of dimension -2126'
    int_3 = None
    axis_error_3 = module_0.AxisError(int_3)
    assert axis_error_3 is not None
    str_3 = axis_error_2.__str__()
    assert str_3 == 'axis -2126 is out of bounds for array of dimension -2126'
    list_0 = []
    dict_0 = {}
    too_hard_error_0 = module_0.TooHardError(**dict_0)
    assert too_hard_error_0 is not None
    complex_warning_2 = module_0.ComplexWarning()
    assert complex_warning_2 is not None
    rank_warning_0 = module_0.RankWarning(**dict_0)
    assert rank_warning_0 is not None
    too_hard_error_1 = module_0.TooHardError()
    assert too_hard_error_1 is not None
    complex_warning_3 = module_0.ComplexWarning(*list_0)
    assert complex_warning_3 is not None
    int_4 = 1696
    axis_error_4 = module_0.AxisError(int_4, int_1)
    assert axis_error_4 is not None