# Automatically generated by Pynguin.
import exceptions_d as module_0

def test_case_0():
    try:
        int_0 = 996
        str_0 = 'h0u:Z4UidR'
        set_0 = {int_0, int_0}
        str_1 = "^ rSUO;Ky#N'"
        str_2 = '!&>JbC6S^&>J'
        dict_0 = {str_0: set_0, str_1: str_0, str_2: str_0}
        rank_warning_0 = module_0.RankWarning(**dict_0)
    except BaseException:
        pass