# Automatically generated by Pynguin.
import loose_version_d as module_0

def test_case_0():
    try:
        str_0 = 'q'
        dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
        loose_version_0 = module_0.LooseVersion(str_0)
        assert loose_version_0.vstring == 'q'
        assert loose_version_0.version == ['q']
        set_0 = set()
        bool_0 = loose_version_0.__le__(set_0)
        assert bool_0 is False
        loose_version_0.parse(str_0)
        loose_version_1 = module_0.LooseVersion(str_0)
        assert loose_version_1.vstring == 'q'
        assert loose_version_1.version == ['q']
        str_1 = loose_version_1.__repr__()
        assert str_1 == "LooseVersion ('q')"
        loose_version_2 = module_0.LooseVersion(str_0)
        assert loose_version_2.vstring == 'q'
        assert loose_version_2.version == ['q']
        bool_1 = loose_version_2.__gt__(str_0)
        assert bool_1 is False
        bool_2 = loose_version_1.__le__(dict_0)
        assert bool_2 is False
        str_2 = None
        loose_version_0.parse(str_2)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = '*sVu H\n\\Gutsc)\r'
        loose_version_0 = module_0.LooseVersion(str_0)
        assert loose_version_0.vstring == '*sVu H\n\\Gutsc)\r'
        assert loose_version_0.version == ['*', 's', 'V', 'u', ' H\n\\G', 'utsc', ')\r']
        str_1 = loose_version_0.__repr__()
        assert str_1 == "LooseVersion ('*sVu H\n\\Gutsc)\r')"
        bool_0 = loose_version_0.__ge__(loose_version_0)
        assert bool_0 is True
        loose_version_1 = module_0.LooseVersion(loose_version_0)
    except BaseException:
        pass