# Automatically generated by Pynguin.
import loose_version_d as module_0

def test_case_0():
    str_0 = "'\n'"
    loose_version_0 = module_0.LooseVersion(str_0)
    assert loose_version_0.vstring == "'\n'"
    assert loose_version_0.version == ["'\n'"]
    loose_version_1 = module_0.LooseVersion(str_0)
    assert loose_version_1.vstring == "'\n'"
    assert loose_version_1.version == ["'\n'"]
    str_1 = loose_version_1.__repr__()
    assert str_1 == "LooseVersion (''\n'')"
    bool_0 = loose_version_1.__le__(str_0)
    assert bool_0 is True

def test_case_1():
    str_0 = 'My$>@'
    none_type_0 = None
    loose_version_0 = module_0.LooseVersion(none_type_0)
    assert loose_version_0 is not None
    loose_version_1 = module_0.LooseVersion(str_0)
    assert loose_version_1.vstring == 'My$>@'
    assert loose_version_1.version == ['M', 'y', '$>@']
    bool_0 = loose_version_1.__ge__(loose_version_1)
    assert bool_0 is True
    set_0 = {str_0}
    str_1 = '/^7H:" &>+y&dY[X%'
    loose_version_2 = module_0.LooseVersion(str_1)
    assert loose_version_2.vstring == '/^7H:" &>+y&dY[X%'
    assert loose_version_2.version == ['/^', 7, 'H:" &>+', 'y', '&', 'd', 'Y[X%']
    bool_1 = loose_version_1.__le__(str_0)
    assert bool_1 is True
    loose_version_2.parse(str_0)
    assert loose_version_2.vstring == 'My$>@'
    assert loose_version_2.version == ['M', 'y', '$>@']
    bool_2 = loose_version_2.__lt__(set_0)
    assert bool_2 is False
    loose_version_3 = module_0.LooseVersion(str_1)
    assert loose_version_3.vstring == '/^7H:" &>+y&dY[X%'
    assert loose_version_3.version == ['/^', 7, 'H:" &>+', 'y', '&', 'd', 'Y[X%']
    bool_3 = loose_version_3.__ge__(set_0)
    assert bool_3 is False
    str_2 = '@DD6.Zy.BNCw.XiCy"an'
    str_3 = 'M'
    loose_version_3.parse(str_3)
    assert loose_version_3.vstring == 'M'
    assert loose_version_3.version == ['M']
    str_4 = ')\r'
    loose_version_4 = module_0.LooseVersion(str_4)
    assert loose_version_4.vstring == ')\r'
    assert loose_version_4.version == [')\r']
    bool_4 = loose_version_4.__ge__(str_0)
    assert bool_4 is False
    loose_version_4.parse(str_2)
    assert loose_version_4.vstring == '@DD6.Zy.BNCw.XiCy"an'
    assert loose_version_4.version == ['@DD', 6, 'Z', 'y', 'BNC', 'w', 'X', 'i', 'C', 'y', '"', 'an']

def test_case_2():
    tuple_0 = ()
    list_0 = [tuple_0, tuple_0]
    str_0 = "}MLf'\n'"
    bool_0 = True
    float_0 = 2950.881
    loose_version_0 = module_0.LooseVersion(str_0)
    assert loose_version_0.vstring == "}MLf'\n'"
    assert loose_version_0.version == ['}ML', 'f', "'\n'"]
    tuple_1 = (bool_0, float_0, list_0, loose_version_0)
    loose_version_1 = module_0.LooseVersion(str_0)
    assert loose_version_1.vstring == "}MLf'\n'"
    assert loose_version_1.version == ['}ML', 'f', "'\n'"]
    bool_1 = loose_version_1.__eq__(tuple_1)
    assert bool_1 is False
    loose_version_2 = module_0.LooseVersion(str_0)
    assert loose_version_2.vstring == "}MLf'\n'"
    assert loose_version_2.version == ['}ML', 'f', "'\n'"]
    bool_2 = loose_version_2.__gt__(list_0)
    assert bool_2 is False

def test_case_3():
    str_0 = 'x'
    str_1 = 'LH\r-bO\x0co41q>-1\t'
    loose_version_0 = module_0.LooseVersion(str_1)
    assert loose_version_0.vstring == 'LH\r-bO\x0co41q>-1\t'
    assert loose_version_0.version == ['LH\r-', 'b', 'O\x0c', 'o', 41, 'q', '>-', 1, '\t']
    str_2 = 'L'
    loose_version_0.parse(str_2)
    assert loose_version_0.vstring == 'L'
    assert loose_version_0.version == ['L']
    loose_version_1 = module_0.LooseVersion(str_1)
    assert loose_version_1.vstring == 'LH\r-bO\x0co41q>-1\t'
    assert loose_version_1.version == ['LH\r-', 'b', 'O\x0c', 'o', 41, 'q', '>-', 1, '\t']
    bool_0 = loose_version_1.__ge__(str_1)
    assert bool_0 is True
    bool_1 = loose_version_0.__lt__(str_0)
    assert bool_1 is True