# Automatically generated by Pynguin.
import resultiterable_d as module_0

def test_case_0():
    str_0 = 'BvPPIeNA7X'
    result_iterable_0 = module_0.ResultIterable(str_0)
    assert len(result_iterable_0) == 10
    assert module_0.TYPE_CHECKING is False
    assert module_0.T_co is not None
    assert module_0.T is not None
    iterator_0 = result_iterable_0.__iter__()

def test_case_1():
    str_0 = 'F}^$(@yR!%'
    result_iterable_0 = module_0.ResultIterable(str_0)
    assert len(result_iterable_0) == 10
    assert module_0.TYPE_CHECKING is False
    assert module_0.T_co is not None
    assert module_0.T is not None
    str_1 = '"-yJkwK\nga*^bLE\t(>N'
    bytes_0 = b'\xe8n\x9d\xf7\xb4H!\xc4\\'
    int_0 = result_iterable_0.__len__()
    assert int_0 == 10
    tuple_0 = ()
    bool_0 = True
    tuple_1 = (str_1, bytes_0, tuple_0, bool_0)
    result_iterable_1 = module_0.ResultIterable(tuple_1)
    assert len(result_iterable_1) == 4
    iterator_0 = result_iterable_0.__iter__()