# Automatically generated by Pynguin.
import builtins as module_0
import _conversions_d as module_1

def test_case_0():
    object_0 = module_0.object()
    bytes_0 = module_1.asbytes(object_0)
    assert module_0.None is None
    assert module_0.False is False
    assert module_0.True is True
    bytes_1 = module_1.asbytes(object_0)
    str_0 = module_1.asunicode(object_0)
    object_1 = None
    bytes_2 = module_1.asbytes(object_1)
    assert bytes_2 == b'None'
    bytes_3 = module_1.asbytes(object_1)
    assert bytes_3 == b'None'