# Automatically generated by Pynguin.
import pytest
import statcounter_d as module_0

def test_case_0():
    try:
        str_0 = 'y#T4irPqa:6/6\x0clNhh'
        float_0 = -3909.4
        stat_counter_0 = module_0.StatCounter()
        assert stat_counter_0.n == 0
        assert stat_counter_0.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_0.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_0.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
        assert stat_counter_0.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
        stat_counter_1 = stat_counter_0.copy()
        assert stat_counter_1.n == 0
        assert stat_counter_1.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_1.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_1.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
        assert stat_counter_1.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
        stat_counter_2 = stat_counter_1.merge(float_0)
        assert stat_counter_1.n == 1
        assert stat_counter_1.mu == pytest.approx(-3909.4, abs=0.01, rel=0.01)
        assert stat_counter_1.maxValue == pytest.approx(-3909.4, abs=0.01, rel=0.01)
        assert stat_counter_1.minValue == pytest.approx(-3909.4, abs=0.01, rel=0.01)
        assert stat_counter_2.n == 1
        assert stat_counter_2.mu == pytest.approx(-3909.4, abs=0.01, rel=0.01)
        assert stat_counter_2.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_2.maxValue == pytest.approx(-3909.4, abs=0.01, rel=0.01)
        assert stat_counter_2.minValue == pytest.approx(-3909.4, abs=0.01, rel=0.01)
        stat_counter_3 = module_0.StatCounter()
        assert stat_counter_3.n == 0
        assert stat_counter_3.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_3.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_3.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
        assert stat_counter_3.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
        stat_counter_4 = stat_counter_3.copy()
        assert stat_counter_4.n == 0
        assert stat_counter_4.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_4.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_4.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
        assert stat_counter_4.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
        list_0 = [str_0]
        stat_counter_5 = module_0.StatCounter(list_0)
    except BaseException:
        pass

def test_case_1():
    try:
        stat_counter_0 = module_0.StatCounter()
        assert stat_counter_0.n == 0
        assert stat_counter_0.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_0.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_0.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
        assert stat_counter_0.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
        float_0 = stat_counter_0.sampleVariance()
        dict_0 = stat_counter_0.asDict()
        assert len(dict_0) == 7
        stat_counter_1 = module_0.StatCounter()
        assert stat_counter_1.n == 0
        assert stat_counter_1.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_1.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
        assert stat_counter_1.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
        assert stat_counter_1.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
        stat_counter_2 = module_0.StatCounter(float_0)
    except BaseException:
        pass