# Automatically generated by Pynguin.
import pytest
import statcounter_d as module_0

def test_case_0():
    float_0 = -2738.26043
    float_1 = -641.0
    float_2 = 2840.412331
    stat_counter_0 = module_0.StatCounter()
    assert stat_counter_0.n == 0
    assert stat_counter_0.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_0.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_0.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_0.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_1 = stat_counter_0.merge(float_2)
    assert stat_counter_0.n == 1
    assert stat_counter_0.mu == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    assert stat_counter_0.maxValue == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    assert stat_counter_0.minValue == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    assert stat_counter_1.n == 1
    assert stat_counter_1.mu == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    assert stat_counter_1.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_1.maxValue == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    assert stat_counter_1.minValue == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    stat_counter_2 = stat_counter_1.copy()
    assert stat_counter_2.n == 1
    assert stat_counter_2.mu == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    assert stat_counter_2.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_2.maxValue == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    assert stat_counter_2.minValue == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    stat_counter_3 = stat_counter_2.merge(float_1)
    assert stat_counter_2.n == 2
    assert stat_counter_2.mu == pytest.approx(1099.7061655, abs=0.01, rel=0.01)
    assert stat_counter_2.m2 == pytest.approx(6060115.909219427, abs=0.01, rel=0.01)
    assert stat_counter_2.minValue == pytest.approx(-641.0, abs=0.01, rel=0.01)
    assert stat_counter_3.n == 2
    assert stat_counter_3.mu == pytest.approx(1099.7061655, abs=0.01, rel=0.01)
    assert stat_counter_3.m2 == pytest.approx(6060115.909219427, abs=0.01, rel=0.01)
    assert stat_counter_3.maxValue == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    assert stat_counter_3.minValue == pytest.approx(-641.0, abs=0.01, rel=0.01)
    stat_counter_4 = stat_counter_3.merge(float_0)
    assert stat_counter_2.n == 3
    assert stat_counter_2.mu == pytest.approx(-179.61603300000002, abs=0.01, rel=0.01)
    assert stat_counter_2.m2 == pytest.approx(15880107.634668667, abs=0.01, rel=0.01)
    assert stat_counter_2.minValue == pytest.approx(-2738.26043, abs=0.01, rel=0.01)
    assert stat_counter_3.n == 3
    assert stat_counter_3.mu == pytest.approx(-179.61603300000002, abs=0.01, rel=0.01)
    assert stat_counter_3.m2 == pytest.approx(15880107.634668667, abs=0.01, rel=0.01)
    assert stat_counter_3.minValue == pytest.approx(-2738.26043, abs=0.01, rel=0.01)
    assert stat_counter_4.n == 3
    assert stat_counter_4.mu == pytest.approx(-179.61603300000002, abs=0.01, rel=0.01)
    assert stat_counter_4.m2 == pytest.approx(15880107.634668667, abs=0.01, rel=0.01)
    assert stat_counter_4.maxValue == pytest.approx(2840.412331, abs=0.01, rel=0.01)
    assert stat_counter_4.minValue == pytest.approx(-2738.26043, abs=0.01, rel=0.01)
    str_0 = stat_counter_4.__repr__()
    assert str_0 == '(count: 3, mean: -179.61603300000002, stdev: 2300.7323207092613, max: 2840.412331, min: -2738.26043)'

def test_case_1():
    bytes_0 = b'\x1d\x14\xdc]!\xcc\x0b\\\xe0\xa8b\xe4'
    stat_counter_0 = module_0.StatCounter(bytes_0)
    assert stat_counter_0.n == 12
    assert stat_counter_0.mu == pytest.approx(118.33333333333333, abs=0.01, rel=0.01)
    assert stat_counter_0.m2 == pytest.approx(81534.66666666666, abs=0.01, rel=0.01)
    assert stat_counter_0.maxValue == 228
    assert stat_counter_0.minValue == 11
    stat_counter_1 = stat_counter_0.copy()
    assert stat_counter_1.n == 12
    assert stat_counter_1.mu == pytest.approx(118.33333333333333, abs=0.01, rel=0.01)
    assert stat_counter_1.m2 == pytest.approx(81534.66666666666, abs=0.01, rel=0.01)
    assert stat_counter_1.maxValue == 228
    assert stat_counter_1.minValue == 11
    float_0 = stat_counter_1.mean()
    assert float_0 == pytest.approx(118.33333333333333, abs=0.01, rel=0.01)
    stat_counter_2 = module_0.StatCounter()
    assert stat_counter_2.n == 0
    assert stat_counter_2.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_2.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_2.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_2.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_3 = stat_counter_2.copy()
    assert stat_counter_3.n == 0
    assert stat_counter_3.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_3.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_3.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_3.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_4 = module_0.StatCounter()
    assert stat_counter_4.n == 0
    assert stat_counter_4.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_4.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_4.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_4.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_5 = stat_counter_4.mergeStats(stat_counter_3)
    assert stat_counter_5.n == 0
    assert stat_counter_5.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_5.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_5.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_5.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    str_0 = stat_counter_4.__repr__()
    assert str_0 == '(count: 0, mean: 0.0, stdev: nan, max: -inf, min: inf)'
    float_1 = stat_counter_4.min()
    assert float_1 == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_2 = stat_counter_5.min()
    assert float_2 == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_3 = stat_counter_3.variance()
    float_4 = stat_counter_4.sampleStdev()
    stat_counter_6 = stat_counter_3.merge(float_1)
    assert stat_counter_3.n == 1
    assert stat_counter_3.mu == pytest.approx(1e309, abs=0.01, rel=0.01)
    assert stat_counter_3.maxValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    assert stat_counter_6.n == 1
    assert stat_counter_6.mu == pytest.approx(1e309, abs=0.01, rel=0.01)
    assert stat_counter_6.maxValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    assert stat_counter_6.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_5 = -1393.218622
    float_6 = stat_counter_5.variance()
    stat_counter_7 = module_0.StatCounter()
    assert stat_counter_7.n == 0
    assert stat_counter_7.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_7.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_7.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_7.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_7 = stat_counter_6.sampleStdev()
    float_8 = stat_counter_2.sampleVariance()
    stat_counter_8 = stat_counter_2.merge(float_6)
    assert stat_counter_2.n == 1
    assert stat_counter_8.n == 1
    assert stat_counter_8.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_8.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_9 = module_0.StatCounter()
    assert stat_counter_9.n == 0
    assert stat_counter_9.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_9.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_9.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_9.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_9 = stat_counter_9.min()
    assert float_9 == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_10 = stat_counter_7.stdev()
    stat_counter_10 = stat_counter_7.copy()
    assert stat_counter_10.n == 0
    assert stat_counter_10.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_10.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_10.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_10.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    int_0 = stat_counter_7.count()
    assert int_0 == 0
    float_11 = stat_counter_7.min()
    assert float_11 == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_12 = stat_counter_7.max()
    assert float_12 == pytest.approx(-1e309, abs=0.01, rel=0.01)
    float_13 = stat_counter_7.sampleVariance()
    float_14 = stat_counter_10.min()
    assert float_14 == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_11 = module_0.StatCounter()
    assert stat_counter_11.n == 0
    assert stat_counter_11.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_11.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_11.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_11.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_15 = stat_counter_7.max()
    assert float_15 == pytest.approx(-1e309, abs=0.01, rel=0.01)
    float_16 = stat_counter_2.sampleVariance()
    stat_counter_12 = stat_counter_7.merge(float_5)
    assert stat_counter_7.n == 1
    assert stat_counter_7.mu == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    assert stat_counter_7.maxValue == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    assert stat_counter_7.minValue == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    assert stat_counter_12.n == 1
    assert stat_counter_12.mu == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    assert stat_counter_12.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_12.maxValue == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    assert stat_counter_12.minValue == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    float_17 = stat_counter_12.sum()
    assert float_17 == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    float_18 = stat_counter_7.stdev()
    assert float_18 == pytest.approx(0.0, abs=0.01, rel=0.01)
    float_19 = stat_counter_3.min()
    assert float_19 == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_13 = stat_counter_12.copy()
    assert stat_counter_13.n == 1
    assert stat_counter_13.mu == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    assert stat_counter_13.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_13.maxValue == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    assert stat_counter_13.minValue == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    float_20 = stat_counter_13.mean()
    assert float_20 == pytest.approx(-1393.218622, abs=0.01, rel=0.01)
    float_21 = stat_counter_2.max()
    assert float_21 == pytest.approx(-1e309, abs=0.01, rel=0.01)

def test_case_2():
    stat_counter_0 = module_0.StatCounter()
    assert stat_counter_0.n == 0
    assert stat_counter_0.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_0.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_0.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_0.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_1 = stat_counter_0.copy()
    assert stat_counter_1.n == 0
    assert stat_counter_1.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_1.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_1.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_1.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_0 = stat_counter_1.min()
    assert float_0 == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_2 = module_0.StatCounter()
    assert stat_counter_2.n == 0
    assert stat_counter_2.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_2.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_2.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_2.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_3 = stat_counter_2.copy()
    assert stat_counter_3.n == 0
    assert stat_counter_3.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_3.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_3.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_3.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_1 = stat_counter_2.min()
    assert float_1 == pytest.approx(1e309, abs=0.01, rel=0.01)
    stat_counter_4 = stat_counter_3.copy()
    assert stat_counter_4.n == 0
    assert stat_counter_4.mu == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_4.m2 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert stat_counter_4.maxValue == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert stat_counter_4.minValue == pytest.approx(1e309, abs=0.01, rel=0.01)
    float_2 = stat_counter_3.sampleStdev()
    float_3 = stat_counter_4.sum()
    assert float_3 == pytest.approx(0.0, abs=0.01, rel=0.01)
    float_4 = stat_counter_3.mean()
    assert float_4 == pytest.approx(0.0, abs=0.01, rel=0.01)